site_name: 服务器编程新手入门 - Server Programming Guide
site_url: https://liuhaohua.com/server-programming-guide/
repo_url: https://github.com/howardlau1999/server-programming-guide/
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
nav:
  - 概览: "index.md"
  - 编译链接基础知识:
    - 概览: "basics/index.md"
    - 编译过程概览: "basics/procedure.md"
    - 静态链接与动态链接: "basics/static-dynamic-linkage.md"
  - 编译系统:
    - 概览: "build-system/index.md"
    - CMake: "build-system/cmake.md"
